import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import * as fcl from "@onflow/fcl";
import "../flow/config.js";
import { MINT_TIME } from "../flow/cadence/transactions/mintTime";

export default function Home() {
  const [User, setUser] = useState();

  useEffect(() => {
    fcl.currentUser.subscribe(setUser);
    fcl.authenticate();
  }, []);

  const handleMint = async () => {
try {
  const txid = await fcl.mutate({
    cadence: MINT_TIME,
    args: (arg, t) => [arg("n1", t.String), arg("n2", t.String), arg("n3", t.String), arg("n4", t.String)],

    limit: 999,
  });

  fcl.tx(txid).subscribe(({ status }) => {
    console.log("status", status);
  });

  console.log("txid", txid);

} catch (error) {
  console.log(error);
}
  
}

    

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Conditional NFTs</h1>
        <p className={styles.description}>
         {User && User.addr}
        </p>

        <div className={styles.grid}>
          <div href="https://nextjs.org/learn" className={styles.card}>
            <h2>Get Non Expired NFTs</h2>
            <p>Description of the function</p>
          </div>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Get Expired NFTs</h2>
            <p>Description of the function</p>
          </a>
          <div onClick={handleMint} className={styles.card}>
            <h2>Mint NFT </h2>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
